# Generated by Django 5.1.4 on 2025-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('current_price', models.FloatField()),
                ('high_52_week', models.FloatField()),
                ('low_52_week', models.FloatField()),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('average_volume_52_week', models.IntegerField(blank=True, null=True)),
                ('cagr_5y', models.FloatField(blank=True, null=True)),
                ('cagr_3y', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('bollinger_bands', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
