# Generated by Django 5.1.4 on 2025-01-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pumpdumpstatus_volumetraderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='dividend_per_share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='dividend_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='historical_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='historical_data_last_30_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='moving_average_200',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='moving_average_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='pe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='volatility',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
