# Generated by Django 5.1.4 on 2025-01-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_nsedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NSEData',
        ),
        migrations.AddField(
            model_name='stockdata',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
