# Generated by Django 5.1.4 on 2025-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_nsedata_stockdata_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
