# Generated by Django 5.1.4 on 2025-01-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_stockdata_high_52_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('high_52_week', models.FloatField(blank=True, null=True)),
                ('low_52_week', models.FloatField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('average_volume_52_week', models.IntegerField(blank=True, null=True)),
                ('cagr_5y', models.FloatField(blank=True, null=True)),
                ('cagr_3y', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('bollinger_bands', models.TextField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('dividend_per_share', models.FloatField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('moving_average_50', models.FloatField(blank=True, null=True)),
                ('moving_average_200', models.FloatField(blank=True, null=True)),
                ('historical_data', models.JSONField(blank=True, null=True)),
                ('historical_data_last_30_days', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='average_volume_52_week',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='bollinger_bands',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='cagr_3y',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='cagr_5y',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='dividend_per_share',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='dividend_yield',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='high_52_week',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='historical_data',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='historical_data_last_30_days',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='low_52_week',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='macd',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='moving_average_200',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='moving_average_50',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='pe_ratio',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='rsi',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='volatility',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='volume',
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='company_name',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
