# Generated by Django 5.1.4 on 2025-01-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_stockdata1_remove_stockdata_average_volume_52_week_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NSEData',
        ),
        migrations.DeleteModel(
            name='PumpDumpStatus',
        ),
        migrations.DeleteModel(
            name='StockData1',
        ),
        migrations.DeleteModel(
            name='VolumeTraderData',
        ),
    ]
