# Generated by Django 5.1.4 on 2025-01-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_nsedata_delete_pumpdumpstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
