# Generated by Django 5.1.4 on 2025-01-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_stockdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
