# Generated by Django 5.1.4 on 2025-01-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_stockdata_company_name_alter_stockdata_symbol'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockdata',
            table='ListOfCompanies',
        ),
    ]
