# Generated by Django 5.1.4 on 2025-01-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_stockdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockdata',
            table=None,
        ),
    ]
